# Generated by Django 3.2.16 on 2022-10-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_width', models.FloatField()),
                ('dimension_height', models.FloatField()),
                ('unit_number', models.IntegerField(unique=True)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
