# Generated by Django 3.2.16 on 2022-10-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage_management', '0004_auto_20221022_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_name',
            new_name='payment_destination',
        ),
    ]
