# Generated by Django 3.2.16 on 2022-11-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage_management', '0005_rename_account_name_transaction_payment_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('business_name', models.CharField(blank=True, max_length=40)),
                ('email_address', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.TextField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=50)),
                ('monthly_charge', models.FloatField()),
                ('contract_start_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('MONTH', 'Monthly'), ('ANNUAL', 'Annually'), ('QUARTERLY', '3mos'), ('SEMESTERLY', '6mos')], default='MONTH', max_length=40)),
                ('last_date_paid', models.DateField()),
                ('last_covered_date', models.DateField()),
                ('documents', models.URLField()),
                ('unit_access', models.ManyToManyField(blank=True, related_name='customers', to='self_storage_management.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_name', to='self_storage_management.client'),
        ),
    ]
