# Generated by Django 3.2.16 on 2022-11-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage_management', '0007_auto_20221126_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='dimension_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='dimension_width',
            field=models.FloatField(),
        ),
    ]
