# Generated by Django 3.2.16 on 2022-11-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage_management', '0008_auto_20221126_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
