# Generated by Django 3.2.16 on 2022-11-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage_management', '0009_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='documents',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='unit_access',
            field=models.ManyToManyField(related_name='units', to='self_storage_management.Unit'),
        ),
    ]
