# Generated by Django 3.2.16 on 2022-11-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_storage_management', '0012_alter_client_unit_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_destination',
            field=models.CharField(choices=[('BBVA', 'BBVA'), ('Azteca - Ziomara', 'Azteca - Ziomara'), ('Costco Citibanamex - Layla', 'Costco Citibanamex - Layla'), ('Oro Citibanamex - Layla', 'Oro Citibanamex - Layla'), ('Costco Citibanamex - Raul', 'Costco Citibanamex - Raul'), ('Santander - Raul', 'Santander - Raul')], max_length=30),
        ),
    ]
